iyi=[]
dadi=[]
rengpt=[]
rengbicr=[]
bulaniq=[]
codluq=[]
elek20=[]
hidrokar=[]
hidrogen=[]
aluminium=[]
nh3=[]
arsen=[}
demir=[]
ag=[]
hidrosulfid=[]
hidrisulfid=[]
cloride=[]
clorfree=[]
cloradd=[]
xlorationu=[]
kalium=[]
kalsium=[]
manqan=[]
mis=[]
molibden=[]
maqnezium=[]
natrium=[]
nikel=[]
nitratlar=[]
nitrit=[]
polifosfat=[]
stronsium=[]
zn=[]
sulfats=[]
sianids=[]
timeline=[]
def qiymet(n):
  n=n-1
  timeline.append(iyi[n])
  timeline.append(dadi[n])
  timeline.append(rengpt[n])
  timeline.append(rengbicr[n])
  timeline.append(bulaniq[n])
  timeline.append(codluq[n])
  timeline.append(elek20[n])
  timeline.append(hidrokar[n])
  timeline.append(hidrogen[n])
  timeline.append(aluminium[n])
  timeline.append(nh3[n])
  timeline.append(arsen[n])
  timeline.append(demir[n])
  timeline.append(ag[n])
  timeline.append(hidrosulfid[n])
  timeline.append(hidrisulfid[n])
  timeline.append(cloride[n])
  timeline.append(clorfree[n])
  timeline.append(cloradd[n])
  timeline.append(xlorationu[n])
  timeline.append(kalium[n])
  timeline.append(kalsium[n])
  timeline.append(manqan[n])
  timeline.append(mis[n])
  timeline.append(molibden[n])
  timeline.append(maqnezium[n])
  timeline.append(natrium[n])
  timeline.append(nikel[n])
  timeline.append(nitratlar[n])
  timeline.append(nitrit[n])
  timeline.append(polifosfat[n])
  timeline.append(stronsium[n])
  timeline.append(zn[n])
  timeline.append(sulfats[n])
  timeline.append(sianids[n])
a=int(input())
print(qiymet(a))

